steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - func
  - --region=asia-south1
  - --source=.
  - --trigger-http
  - --runtime=ruby 2.6
