steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'echo Password=$$PASSWORD && echo USERNAME=$$USERNAME']
  secretEnv: ['PASSWORD', 'USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SECRET2/versions/1
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/SECRET1/versions/1
    env: 'USERNAME'
 

      
   
