steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'serverise', '--image', 'gcr.io/solution-kit-2/15a2d0879c22', '--region', 'asia-south1']
images:
- gcr.io/solution-kit-2/15a2d0879c22

  containerConcurrency: 80
  timeoutSeconds: 300
  containers:
  - image: us.gcr.io/project-test/express-image:1.0
    ports:
    - name: http1
      containerPort: 8080
    resources:
      limits:
        memory: 256Mi
        cpu: 1000m 
