steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/HerokuMigration/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/HerokuMigration/15a2d0879c22']
  
  

