steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'serverise', '--image', 'gcr.io/solution-kit-2/15a2d0879c22', '--region', 'asia-south1']
images:
- gcr.io/solution-kit-2/15a2d0879c22

