steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/herukomigration/15a2d0879c22', '.' ]



steps:
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "Secret key 'TEST' has value '$$TEST'"
  secretEnv: ['TEST']
  
availableSecrets:
  secretManager:
  - versionName: projects/herokumigration/secrets/TEST/versions/1
    env: 'TEST'
  
    

      
   
