steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']
  - '-c'
  - |
      if [ -m "CF_COMMIT_MESSAGE" == 'deploy']; then
        echo deploy
      else
        echo commit
      fi
