steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/herukomigration/15a2d0879c22', '.' ]
  
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SECRET1/versions/1
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/SECRET2/versions/latest
    env: 'USERNAME'
  
    
steps: 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  
  args:
  - '-c'
  - |
      if [ ${_COMMIT_MESSAGE} = "push" ]; then
        push;
      fi
 

