
steps:
- name: 'launcher.gcr.io/google/ubuntu1604'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    echo "Secret key 'SECRET1' has value '$$SOMVAR1'"
  secretEnv: ['SOMVAR1']
  
availableSecrets:
  secretManager:
  - versionName: projects/herokumigration/secrets/SECRET1/versions/1
    env: 'SOMVAR1'
  
    

      
   
