steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  
   if [[ "message=str(input(' '))" == "deploy" ]]; then
     name: 'commit'
  - --filename= config.yaml
  - --location=	us-central1-c
  - --cluster=cluster-1
