
 steps:
- name: 'launcher.gcr.io/google/ubuntu1604'
  id: Create GitHub pull request
  entrypoint: bash
  args:
  - -c
  - curl -X POST -H "Authorization:Bearer $$GH_TOKEN" -H 'Accept:application/vnd.github.v3+json' https://api.github.com/repos/KbansalMA23/CI-CD-cloud_build/pulls -d '{"head":"main","base":"prod", "title":"pull request"}'
  secretEnv: ['GH_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/herukomigration/secrets/github-cloud-cicd/versions/latest
    env: GH_TOKEN

