steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']
  
- name: "gcr.io/cloud-builders/gke-deploy"
  id: deploy
   args:
      if [ [ $COMMIT_MESSAGE = "deploy" ] ]; then
       git commit
      else
        git push
      fi
    
