steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']
  
- name: "gcr.io/cloud-builders/gke-deploy"
      when:
        condition:
          all:
              deployInCommitMessage: |
                  includes(lower("${{CF_COMMIT_MESSAGE}}"), "--deploy") == true
