steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']

steps:
...
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=usr/lib/google-cloud-sdk/bin/gcloud
  - --location=	us-central1-c
  - --cluster=cluster-1
