steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/solution-kit-2/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/solution-kit-2/15a2d0879c22']

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename= config.yaml
  - --location=	us-central1-c
  - --cluster=cluster-1
