steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/herukomigration/15a2d0879c22', '.' ]
  
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', ". ./cloudbuilds/script.sh $$TEST"]
  secretEnv: ['TEST']
availableSecrets:
  secretManager:
  - versionName: projects/herokumigration/secrets/TEST/versions/1
    env: 'TEST'
  
    
steps: 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  
  args:
  - '-c'
  - |
      if [ ${_COMMIT_MESSAGE} = "push" ]; then
        push;
      fi
 

