steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/herukomigration/15a2d0879c22', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['gcr.io/herukomigration/15a2d0879c22']
  
  args:
  - '-c'
  - |
      if ["COMMIT_MESSAGE"= 'push']; then
        Push
      else
        Commit
      fi
  

