- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/solution-kit-2/15a2d0879c22:$SHORT_SHA'
  - '.'
  - name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/solution-kit-2/15a2d0879c22:$SHORT_SHA'
